apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-creditevaluation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-creditevaluation-deployment
  template:
    metadata:
      labels:
        app: ms-creditevaluation-deployment
    spec:
      containers:
        - name: ms-creditevaluation-container
          image: fabian3050/ms-creditevaluation:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_FINANCIAL_EVALUATION
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_FINANCIAL_EVALUATION
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD