apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-totalcost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-totalcost-deployment
  template:
    metadata:
      labels:
        app: ms-totalcost-deployment
    spec:
      containers:
        - name: ms-totalcost-container
          image: fabian3050/ms-totalcost:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://localhost:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://localhost:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_TOTALCOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_TOTALCOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD